#!/bin/bash
# Activate the virtual environment
source /Users/esa02/repos/scripts/ed/setup/ed_venv/bin/activate
# Run the Python script with the provided arguments
python /Users/esa02/repos/scripts/ed/ed.py "$@"
